config/routes.rb
Rails.application.routes.draw do

  resources :cocktails do #, only: [:index, :show, :new, :create]
    resources :doses, only: [ :index, :new, :create ]
  end

  resources :doses, only:  [ :show, :edit, :update, :destroy ]

  root 'cocktails#index'
  # A user can see the list of cocktails
  # GET "cocktails"

  # A user can see the details of a given cocktail, with the dose needed for each ingredien
  # GET "cocktails/42"

  # A user can create a new cocktail
  # GET "cocktails/new"
  # POST "cocktails"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :cocktail, scope: :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true

  def destroy
    raise ActiveRecord::InvalidForeignKey unless doses.count.zero?

    super
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @ingredients = Ingredient.all
    @cocktail = Cocktail.new
  end

  def edit
    @ingredients = Ingredient.all
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    if @cocktail.update(cocktail_params)
      redirect_to cocktail_path
    else
      render :edit
    end
  end

  def create
    @cocktail = Cocktail.create(cocktail_params)
    if @cocktail.save
      @ingredient = Ingredient.find_by(name: params[:cocktail][:ingredients])
      @dose = Dose.create(description: params[:cocktail][:doses])
      @dose.cocktail = @cocktail
      @dose.ingredient = @ingredient
      if @dose.save
        redirect_to cocktail_path(@cocktail)
      else
        render :new
      end
    else
        render :new
    end
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def index
    @doses = Dose.all
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredients = Ingredient.all
    @dose = Dose.new
  end

  def create
    @ingredient = Ingredient.find_by(name: params[:dose][:ingredient_id])
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(description: params[:dose][:description])
    @dose.ingredient = @ingredient
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render new_cocktail_dose_path(@cocktail)
    end
  end

  private

  def dose_params
    params.require(:dose).permit(:create)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/dose_helper.rb
module DoseHelper
end

app/views/cocktails/edit.html.erb
<div class="row">
  <h1>Edit Cocktail Name</h1>
</div>
<div class="row">
  <%= simple_form_for(@cocktail, html: {class: "p-3 border shadow"}) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-group">
    <div class="form-inputs">
      <%= f.input :name %>
    </div>
  </div>
<!--     <div class="form-dose">
      <div class="form-row">
      <div class="form-group col-md-6">
        <div class="form-inputs">
        <%= f.input :doses, placeholder: 'Dose', collection: ['1cl', '2cl', '3cl', '4cl', '5cl'], prompt: "Select amount" %>
        </div>
      </div>
      <div class="form-group col-md-6">
        <div class="form-inputs">
          <%= f.input :ingredients, placeholder: 'Ingredient', collection: @ingredients.pluck(:name), prompt: "Select ingredient" %>
        </div>
      </div>
    </div> -->
  </div>
<!--     <a href="#" id="add-ingredient">+ Ingredient</a> -->
  <div class="form-actions">
    <%= f.submit "Update cocktail name", class: "btn btn-primary" %>
  </div>
  <% end %>
</div>
<div class="row">
  <%= link_to "<< Back", cocktail_path(@cocktail), class: "btn btn-primary mt-3" %>
</div>

app/views/cocktails/index.html.erb
<div class="row d-flex justify-content-between align-items-center">
  <div class="col-9"><h1>All Cocktails</h1></div>
  <div class="col-3"><%= link_to "Add New Cocktail", new_cocktail_path, class: "btn btn-primary" %></div>
</div>
<div class="row d-flex justify-content-around">
  <% @cocktails.each do |c| %>
  <div class="col-3">
    <div class="card mt-5" style="width: 18rem;">
      <img class="card-img-top" src="https://source.unsplash.com/600x400/?cocktail&<%= c.name %>" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"><%= link_to c.name, cocktail_path(c) %></h5>
        <p class="card-text">
          <h6>Ingredients</h6>
          <ul class="list-unstyled">
            <% c.doses.each do |d| %>
            <li><%= d.description %> of <%= d.ingredient.name %></li>
            <% end %>
          </ul>

        </p>
        <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<div class="container mx-auto w-50">
  <div class="row">
    <h1>Add New Cocktail</h1>
  </div>
  <div class="row">
    <%= simple_form_for(@cocktail, html: {class: "p-3 border shadow"}) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-group">
      <div class="form-inputs">
        <%= f.input :name %>
      </div>
    </div>
    <div class="form-dose">
      <div class="form-row">
        <div class="form-group col-md-6">
          <div class="form-inputs">
          <%= f.input :doses, placeholder: 'Dose', collection: ['1cl', '2cl', '3cl', '4cl', '5cl'], prompt: "Select amount" %>
          </div>
        </div>
        <div class="form-group col-md-6">
          <div class="form-inputs">
            <%= f.input :ingredients, placeholder: 'Ingredient', collection: @ingredients.pluck(:name), prompt: "Select ingredient" %>
          </div>
        </div>
      </div>
    </div>
    <a href="#" id="add-ingredient">+ Ingredient (WIP)</a>
    <div class="form-actions">
      <%= f.submit "Submit new cocktail", class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>
  <div class="row">
    <%= link_to "<< All Cocktails", cocktails_path, class: "btn btn-primary mt-3" %>
  </div>
</div>

app/views/cocktails/show.html.erb
<h1>This is an awesome cocktail</h1>
<div class="row">
  <div class="card mb-3">
    <img class="card-img-top" src="https://source.unsplash.com/600x400/?cocktail" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title"><%= @cocktail.name %></h5>
      <%= link_to "Edit Cocktail Name", edit_cocktail_path, class: "btn btn-secondary mt-3" %>
      <p class="card-text">
        <h6>Ingredients</h6>
        <ul class="list-unstyled">
          <% @cocktail.doses.each do |d| %>
          <li><%= d.description %> of <%= d.ingredient.name %></li>
          <% end %>
        </ul>
        <%= link_to "Add Ingredient", new_cocktail_dose_path(@cocktail), class: "btn btn-secondary mt-3" %>
      </p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
  </div>
  <%= link_to "<< All Cocktails", cocktails_path, class: "btn btn-primary mt-3" %>

</div>

app/views/doses/new.html.erb
<div class="row">
  <h1>Add a dose</h1>
</div>
<div class="row">
  <div class="col-9">
    <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <div class="form-inputs">
        <%= f.input :description, placeholder: 'Dose', collection: ['1cl', '2cl', '3cl', '4cl', '5cl'], prompt: "Select amount" %>
        <%= f.input :ingredient_id, placeholder: 'Ingredient', collection: @ingredients.pluck(:name), prompt: "Select ingredient" %>
      </div>
      <div class="form-actions">
        <%= f.submit "Submit new doses", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <div class="main p-5 mx-auto">
      <%= yield %>
      <%= javascript_include_tag 'application' %>
      <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
    </div>
  </body>
</html>